sudo: required
services:
  - docker

before_install:
  - docker build -t mcadams0001/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mcadams0001/complex-test npm run test -- --coverage

after_success:
  - docker build -t mcadams0001/multi-client ./client
  - docker build -t mcadams0001/multi-nginx ./nginx
  - docker build -t mcadams0001/multi-server ./server
  - docker build -t mcadams0001/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mcadams0001/multi-client
  - docker push mcadams0001/multi-nginx
  - docker push mcadams0001/multi-server
  - docker push mcadams0001/multi-worker

